# Generated by Django 5.1.1 on 2024-11-15 10:15

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0002_menucategory_level_menucategory_lft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='menucategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='restaurantapp.restaurant'),
            preserve_default=False,
        ),
    ]
