# Generated by Django 5.1.1 on 2024-11-15 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0003_remove_menucategory_restaurants_menucategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_categories', to='restaurantapp.restaurant'),
        ),
    ]
