# Generated by Django 5.1.1 on 2024-11-15 10:20

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0007_remove_menucategory_parent_menucategory_restaurants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='restaurants',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_categories', to='restaurantapp.restaurant'),
        ),
    ]
