# Generated by Django 5.1.3 on 2024-11-16 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0013_alter_restaurant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='menu_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='restaurantapp.menusubcategory'),
        ),
    ]
